package com.example.agentservice.procurement.service;

import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableCell;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPageMar;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTSectPr;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.OutputStream;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/** Renders the Markdown subset generated by procurement agents into a generic A4 DOCX. */
@Service
public class TenderMarkdownDocxRenderer {

    public void render(String markdown, Path output) throws IOException {
        if (markdown == null || markdown.isBlank()) {
            throw new IllegalArgumentException("定稿 Markdown 不能为空");
        }
        if (output == null) {
            throw new IllegalArgumentException("DOCX 输出路径不能为空");
        }
        Path parent = output.toAbsolutePath().getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        try (XWPFDocument document = new XWPFDocument(); OutputStream stream = Files.newOutputStream(output)) {
            configureA4(document);
            List<String> lines = markdown.replace("\r\n", "\n").replace('\r', '\n').lines().toList();
            for (int index = 0; index < lines.size();) {
                String line = lines.get(index).trim();
                if (line.isBlank() || line.equals("---")) {
                    index++;
                    continue;
                }
                if (isTableLine(line)) {
                    List<String> tableLines = new ArrayList<>();
                    while (index < lines.size() && isTableLine(lines.get(index).trim())) {
                        tableLines.add(lines.get(index).trim());
                        index++;
                    }
                    appendTable(document, tableLines);
                    continue;
                }
                appendParagraph(document, line);
                index++;
            }
            document.write(stream);
        }
    }

    private void configureA4(XWPFDocument document) {
        CTSectPr section = document.getDocument().getBody().isSetSectPr()
                ? document.getDocument().getBody().getSectPr()
                : document.getDocument().getBody().addNewSectPr();
        section.addNewPgSz().setW(BigInteger.valueOf(11906));
        section.getPgSz().setH(BigInteger.valueOf(16838));
        CTPageMar margin = section.addNewPgMar();
        margin.setTop(BigInteger.valueOf(1440));
        margin.setBottom(BigInteger.valueOf(1440));
        margin.setLeft(BigInteger.valueOf(1440));
        margin.setRight(BigInteger.valueOf(1440));
    }

    private void appendParagraph(XWPFDocument document, String line) {
        XWPFParagraph paragraph = document.createParagraph();
        int headingLevel = headingLevel(line);
        String text = headingLevel > 0 ? line.substring(headingLevel + 1).trim() : stripListPrefix(line);
        XWPFRun run = paragraph.createRun();
        run.setText(stripInlineMarkdown(text));
        run.setFontFamily("宋体");
        if (headingLevel > 0) {
            paragraph.setStyle("Heading" + Math.min(headingLevel, 3));
            run.setBold(true);
            run.setFontSize(Math.max(14, 20 - headingLevel * 2));
        } else {
            run.setFontSize(11);
            if (isListItem(line)) {
                paragraph.setIndentationLeft(420);
            }
        }
    }

    private void appendTable(XWPFDocument document, List<String> lines) {
        List<List<String>> rows = lines.stream()
                .filter(line -> !isTableSeparator(line))
                .map(this::tableCells)
                .filter(cells -> !cells.isEmpty())
                .toList();
        if (rows.isEmpty()) {
            return;
        }
        int columns = rows.stream().mapToInt(List::size).max().orElse(1);
        XWPFTable table = document.createTable(rows.size(), columns);
        for (int rowIndex = 0; rowIndex < rows.size(); rowIndex++) {
            XWPFTableRow row = table.getRow(rowIndex);
            List<String> values = rows.get(rowIndex);
            for (int columnIndex = 0; columnIndex < columns; columnIndex++) {
                XWPFTableCell cell = row.getCell(columnIndex);
                cell.removeParagraph(0);
                XWPFParagraph paragraph = cell.addParagraph();
                XWPFRun run = paragraph.createRun();
                run.setText(stripInlineMarkdown(columnIndex < values.size() ? values.get(columnIndex) : ""));
                run.setFontFamily("宋体");
                run.setFontSize(10);
                run.setBold(rowIndex == 0);
            }
        }
    }

    private boolean isTableLine(String line) {
        return line.startsWith("|") && line.endsWith("|");
    }

    private boolean isTableSeparator(String line) {
        return line.matches("^\\|[ :|\\-]+\\|$");
    }

    private List<String> tableCells(String line) {
        String content = line.substring(1, line.length() - 1);
        String[] values = content.split("\\|", -1);
        List<String> cells = new ArrayList<>(values.length);
        for (String value : values) {
            cells.add(value.trim().replace("<br>", "\n"));
        }
        return cells;
    }

    private int headingLevel(String line) {
        int level = 0;
        while (level < line.length() && line.charAt(level) == '#') {
            level++;
        }
        return level > 0 && level < line.length() && line.charAt(level) == ' ' ? level : 0;
    }

    private boolean isListItem(String line) {
        return line.startsWith("- ") || line.matches("^\\d+\\.\\s+.*");
    }

    private String stripListPrefix(String line) {
        return line.replaceFirst("^(?:- |\\d+\\.\\s+)", "");
    }

    private String stripInlineMarkdown(String text) {
        return text.replace("**", "").replace("`", "");
    }
}
